export const queryKeys = {
  user: "user",
  me: "me",
  checklist: "checklist",
  sample: "sample",
  test: "test",
  appointment: "appointment",
  users: "users",
  pending: "pending",
  appointmentAccepted: "appointmentAccepted",
  completed: "completed",
  total: "total",
  testCompleted: "testCompleted",
  collectSample: "collectSample",
  dispatchAcceptOrder: "dispatchAcceptOrder",
  sampleDelivered: "sampleDelivered",
};
