const USERLIST = [
  {
    name: "John Doe",
    company: "Acme Inc.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Jane Smith",
    company: "XYZ Corp.",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Bob Johnson",
    company: "ABC Co.",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Alice Lee",
    company: "123 LLC",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Tom Wilson",
    company: "Acme Inc.",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Sara Brown",
    company: "XYZ Corp.",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Mike Davis",
    company: "ABC Co.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Emily Chen",
    company: "123 LLC",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "David Kim",
    company: "Acme Inc.",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Karen Lee",
    company: "XYZ Corp.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Peter Wong",
    company: "ABC Co.",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Lisa Chen",
    company: "123 LLC",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Timothy Lee",
    company: "Acme Inc.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Grace Kim",
    company: "XYZ Corp.",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Daniel Park",
    company: "ABC Co.",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Olivia Lee",
    company: "123 LLC",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Michael Chen",
    company: "Acme Inc.",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Sophia Kim",
    company: "XYZ Corp.",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Erica Lee",
    company: "ABC Co.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "William Park",
    company: "123 LLC",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Jessica Lee",
    company: "Acme Inc.",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Ryan Chen",
    company: "XYZ Corp.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Natalie Kim",
    company: "ABC Co.",
    role: "Designer",
    isVerified: false,
    status: "Inactive",
  },
  {
    name: "Kevin Park",
    company: "123 LLC",
    role: "Manager",
    isVerified: true,
    status: "Active",
  },
  {
    name: "Ava Lee",
    company: "Acme Inc.",
    role: "Developer",
    isVerified: true,
    status: "Active",
  },
];
